#!/bin/bash
# configure_tracer.sh — run on the HOST. Turns a guest_config.txt (from
# probe_guest.sh) into a ready-to-run run_trace.sh plus a
# trace_metadata.txt provenance sidecar.
#
# Usage:
#   ./configure_tracer.sh <guest_config.txt> [outdir]
# Options via env:
#   QEMU=<path>       qemu-system-aarch64 binary   (default: from PATH)
#   PLUGIN=<path>     champsim_tracer.so           (default: ../../plugin/champsim_tracer.so)
#   VCPUS=<range>     vCPUs to trace               (default: 0)
#   LIMIT=<N>         insns per vCPU               (default: 1000000000)
set -u

GUEST_CFG="${1:?usage: configure_tracer.sh <guest_config.txt> [outdir]}"
OUTDIR="${2:-$PWD/traces_out}"
KIT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN="${PLUGIN:-$KIT_DIR/../../plugin/champsim_tracer.so}"
QEMU="${QEMU:-$(command -v qemu-system-aarch64 || true)}"
VCPUS="${VCPUS:-0}"
LIMIT="${LIMIT:-1000000000}"
TRIGGER="/tmp/trace_start"

die() { echo "ERROR: $*" >&2; exit 1; }
warn() { echo "WARNING: $*" >&2; }

[ -r "$GUEST_CFG" ] || die "cannot read $GUEST_CFG"

# --- QEMU checks ---
[ -n "$QEMU" ] && [ -x "$QEMU" ] || die "qemu-system-aarch64 not found.
Set QEMU=/path/to/qemu-system-aarch64 (must be built with --enable-plugins)."
QV_RAW="$("$QEMU" --version | head -1)"
QV=$(echo "$QV_RAW" | grep -oE '[0-9]+\.[0-9]+' | head -1)
QMAJ=${QV%%.*}; QMIN=${QV##*.}
if [ "$QMAJ" -lt 9 ] || { [ "$QMAJ" -eq 9 ] && [ "$QMIN" -lt 1 ]; }; then
    die "QEMU $QV is too old: the plugin's value capture needs >= 9.1
(qemu_plugin_mem_get_value). Upgrade QEMU or rebuild from source."
fi

# --- Plugin checks ---
[ -r "$PLUGIN" ] || die "plugin not found at $PLUGIN.
Build it first: cd <repo>/plugin && ./build_plugin.sh <qemu-source-tree>"
PLUGIN_COMMIT=$(strings "$PLUGIN" | grep -m1 '^CSTF_COMMIT=' | cut -d= -f2)
PLUGIN_COMMIT="${PLUGIN_COMMIT:-UNKNOWN=no-embedded-commit-string}"

# --- Running-guest CPU/machine discovery (best effort) ---
MAPS=$(pgrep -a -f qemu-system-aarch64 2>/dev/null | grep -v configure_tracer || true)
NGUEST=$(echo "$MAPS" | grep -c . || true)
CPU_MODEL_QEMU="UNKNOWN=no-running-guest"
MACHINE_QEMU="UNKNOWN=no-running-guest"
if [ "${NGUEST:-0}" -ge 1 ]; then
    LINE=$(echo "$MAPS" | head -1)
    [ "$NGUEST" -gt 1 ] && warn "multiple qemu-system-aarch64 processes; using the first"
    CPU_MODEL_QEMU=$(echo "$LINE" | grep -oE '\-cpu [^ ]+' | cut -d' ' -f2)
    MACHINE_QEMU=$(echo "$LINE" | grep -oE '\-machine [^ ]+' | cut -d' ' -f2)
    CPU_MODEL_QEMU="${CPU_MODEL_QEMU:-UNKNOWN=no--cpu-flag-visible}"
    MACHINE_QEMU="${MACHINE_QEMU:-UNKNOWN=no--machine-flag-visible}"
fi

mkdir -p "$OUTDIR"

# --- Sidecar ---
META="$KIT_DIR/trace_metadata.txt"
{
    cat "$GUEST_CFG"
    echo "QEMU_BIN=$QEMU"
    echo "QEMU_VERSION=$QV_RAW"
    echo "HOST_ARCH=$(uname -m)"
    echo "CPU_MODEL_QEMU=$CPU_MODEL_QEMU"
    echo "MACHINE_QEMU=$MACHINE_QEMU"
    echo "TRACE_ARCH=aarch64"
    echo "CAPTURE_PA=on"
    echo "VALUES=on"
    echo "VALUE_CAP=16"
    echo "LIMIT=$LIMIT"
    echo "VCPUS=$VCPUS"
    echo "TRIGGER=$TRIGGER"
    echo "OUTDIR=$OUTDIR"
    echo "PLUGIN_SO=$PLUGIN"
    echo "PLUGIN_COMMIT=$PLUGIN_COMMIT"
    echo "GENERATED_AT=$(date -Iseconds)"
} > "$META"

# --- run_trace.sh ---
RUN="$KIT_DIR/run_trace.sh"
cat > "$RUN" <<RUNEOF
#!/bin/bash
# run_trace.sh — GENERATED by configure_tracer.sh $(date -Iseconds)
# Traces vCPUs $VCPUS for $LIMIT insns each. Tracing is DORMANT until
# you run:   touch $TRIGGER     (on this host)
set -u

# ── Two-phase vs single-phase ────────────────────────────────────────
# SNAPSHOT="name"  -> restore a KVM-taken snapshot under TCG (two-phase).
#                     Run the KVM smoke test in the README FIRST.
# SNAPSHOT=""      -> cold boot under TCG (single-phase; always works).
SNAPSHOT=""

OUTDIR="$OUTDIR"
mkdir -p "\$OUTDIR"
cp "$META" "\$OUTDIR/trace_metadata.txt"   # sidecar travels with the traces

LOADVM=()
[ -n "\$SNAPSHOT" ] && LOADVM=(-loadvm "\$SNAPSHOT")

"$QEMU" \\
    -machine virt \\
    -accel tcg,thread=multi \\
    -smp 4 -m 4G \\
    -nographic -serial mon:stdio \\
    -plugin "$PLUGIN",outdir="\$OUTDIR",vcpus=$VCPUS,limit=$LIMIT,trigger=$TRIGGER,capture_pa=on,values=on \\
    "\${LOADVM[@]}" \\
    #
    # ─── YOUR BOOT FLAGS GO HERE (replace this comment block) ────────
    # Add your usual -cpu, -drive, pflash firmware, -nic, cloud-init
    # seed, etc. — everything you normally boot this guest with, minus
    # any -accel/-machine flags (already set above; -cpu note: TCG
    # cannot use 'host'; use a named model, e.g. -cpu cortex-a76).
    # ─────────────────────────────────────────────────────────────────
RUNEOF
chmod +x "$RUN"

echo "OK: wrote $RUN"
echo "OK: wrote $META"
echo "Next: edit the boot-flags block in run_trace.sh, then see README.md"
