#!/bin/bash
# configure_tracer.sh — run on the HOST. Turns a guest_config.txt (from
# probe_guest.sh) into a ready-to-run run_trace.sh plus a
# trace_metadata.txt provenance sidecar.
#
# Usage:
#   ./configure_tracer.sh <guest_config.txt> [outdir]
# Options via env:
#   QEMU=<path>       qemu-system-aarch64 binary   (default: from PATH)
#   PLUGIN=<path>     champsim_tracer.so           (default: ../../plugin/champsim_tracer.so)
#   VCPUS=<range>     vCPUs to trace               (default: 0)
#   LIMIT=<N>         insns per vCPU               (default: 1000000000)
set -u

GUEST_CFG="${1:?usage: configure_tracer.sh <guest_config.txt> [outdir]}"
OUTDIR="${2:-$PWD/traces_out}"
KIT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN="${PLUGIN:-$KIT_DIR/../../plugin/champsim_tracer.so}"
QEMU="${QEMU:-$(command -v qemu-system-aarch64 || true)}"
VCPUS="${VCPUS:-0}"
LIMIT="${LIMIT:-1000000000}"
TRIGGER="/tmp/trace_start"

die() { echo "ERROR: $*" >&2; exit 1; }
warn() { echo "WARNING: $*" >&2; }

[ -r "$GUEST_CFG" ] || die "cannot read $GUEST_CFG"

# --- QEMU checks ---
[ -n "$QEMU" ] && [ -x "$QEMU" ] || die "qemu-system-aarch64 not found.
Set QEMU=/path/to/qemu-system-aarch64 (must be built with --enable-plugins)."
QV_RAW="$("$QEMU" --version 2>&1 | head -1)"
NOT_QEMU_MSG="could not confirm '$QEMU' is really qemu-system-aarch64
(its --version output was: '$QV_RAW'). Set QEMU=/path/to/qemu-system-aarch64."
# Reject anything whose --version output doesn't even claim to be QEMU.
# This also defeats the GNU-coreutils false-positive: '/bin/false --version'
# prints "false (GNU coreutils) 9.4", which contains a syntactically valid
# X.Y pair that would otherwise sail through the numeric check below.
case "$QV_RAW" in
    *QEMU*) : ;;
    *) die "$NOT_QEMU_MSG" ;;
esac
QV=$(echo "$QV_RAW" | grep -oE '[0-9]+\.[0-9]+' | head -1)
# Reject empty/unparseable version strings before doing arithmetic on them —
# `[ "$QMAJ" -lt 9 ]` with an empty or non-numeric operand is a bash "integer
# expression expected" ERROR (not a false condition), which used to let an
# unvalidated QEMU slip through silently.
case "$QV" in
    ''|*[!0-9.]*) die "$NOT_QEMU_MSG" ;;
esac
QMAJ=${QV%%.*}; QMIN=${QV##*.}
case "$QMAJ" in ''|*[!0-9]*) die "$NOT_QEMU_MSG" ;; esac
case "$QMIN" in ''|*[!0-9]*) die "$NOT_QEMU_MSG" ;; esac
if [ "$QMAJ" -lt 9 ] || { [ "$QMAJ" -eq 9 ] && [ "$QMIN" -lt 1 ]; }; then
    die "QEMU $QV is too old: the plugin's value capture needs >= 9.1
(qemu_plugin_mem_get_value). Upgrade QEMU or rebuild from source."
fi

# --- Plugin checks ---
[ -r "$PLUGIN" ] || die "plugin not found at $PLUGIN.
Build it first: cd <repo>/plugin && ./build_plugin.sh <qemu-source-tree>"
PLUGIN_COMMIT=$(strings "$PLUGIN" | grep -m1 '^CSTF_COMMIT=' | cut -d= -f2)
PLUGIN_COMMIT="${PLUGIN_COMMIT:-UNKNOWN=no-embedded-commit-string}"

# --- Running-guest CPU/machine discovery (best effort) ---
MAPS=$(pgrep -a -f qemu-system-aarch64 2>/dev/null | grep -v configure_tracer || true)
NGUEST=$(echo "$MAPS" | grep -c . || true)
CPU_MODEL_QEMU="UNKNOWN=no-running-guest"
MACHINE_QEMU="UNKNOWN=no-running-guest"
if [ "${NGUEST:-0}" -ge 1 ]; then
    LINE=$(echo "$MAPS" | head -1)
    [ "$NGUEST" -gt 1 ] && warn "multiple qemu-system-aarch64 processes; using the first"
    CPU_MODEL_QEMU=$(echo "$LINE" | grep -oE '\-cpu [^ ]+' | cut -d' ' -f2)
    MACHINE_QEMU=$(echo "$LINE" | grep -oE '\-machine [^ ]+' | cut -d' ' -f2)
    CPU_MODEL_QEMU="${CPU_MODEL_QEMU:-UNKNOWN=no--cpu-flag-visible}"
    MACHINE_QEMU="${MACHINE_QEMU:-UNKNOWN=no--machine-flag-visible}"
fi

mkdir -p "$OUTDIR"

# --- Sidecar ---
META="$KIT_DIR/trace_metadata.txt"
{
    # `sed -e '$a\'` (append an empty line after the last line) forces a
    # trailing newline even if $GUEST_CFG lacks one — plain `cat` would let
    # the next `echo` below get concatenated onto the guest config's last
    # KEY=VALUE line instead of starting its own.
    sed -e '$a\' "$GUEST_CFG"
    echo "QEMU_BIN=$QEMU"
    echo "QEMU_VERSION=$QV_RAW"
    echo "HOST_ARCH=$(uname -m)"
    echo "CPU_MODEL_QEMU=$CPU_MODEL_QEMU"
    echo "MACHINE_QEMU=$MACHINE_QEMU"
    echo "TRACE_ARCH=aarch64"
    echo "CAPTURE_PA=on"
    echo "VALUES=on"
    echo "VALUE_CAP=16"
    echo "LIMIT=$LIMIT"
    echo "VCPUS=$VCPUS"
    echo "TRIGGER=$TRIGGER"
    echo "OUTDIR=$OUTDIR"
    echo "PLUGIN_SO=$PLUGIN"
    echo "PLUGIN_COMMIT=$PLUGIN_COMMIT"
    echo "GENERATED_AT=$(date -Iseconds)"
} > "$META"

# --- run_trace.sh ---
RUN="$KIT_DIR/run_trace.sh"
cat > "$RUN" <<RUNEOF
#!/bin/bash
# run_trace.sh — GENERATED by configure_tracer.sh $(date -Iseconds)
# Traces vCPUs $VCPUS for $LIMIT insns each. Tracing is DORMANT until
# you run:   touch $TRIGGER     (on this host)
set -u

# ── Two-phase vs single-phase ────────────────────────────────────────
# SNAPSHOT="name"  -> restore a KVM-taken snapshot under TCG (two-phase).
#                     Run the KVM smoke test in the README FIRST.
# SNAPSHOT=""      -> cold boot under TCG (single-phase; always works).
SNAPSHOT=""

# ── vCPU count / RAM size ────────────────────────────────────────────
# Also preset here, just like SNAPSHOT= above — edit THESE two variables
# to match your guest, don't paste a second -smp/-m into the boot-flags
# block below (QEMU accepts duplicates silently; last one wins, which
# is easy to miss).
SMP=4
MEM=4G

OUTDIR="$OUTDIR"
mkdir -p "\$OUTDIR"
cp "$META" "\$OUTDIR/trace_metadata.txt"   # sidecar travels with the traces

LOADVM=()
[ -n "\$SNAPSHOT" ] && LOADVM=(-loadvm "\$SNAPSHOT")

"$QEMU" \\
    -machine virt \\
    -accel tcg,thread=multi \\
    -smp "\$SMP" -m "\$MEM" \\
    -nographic -serial mon:stdio \\
    -plugin "$PLUGIN",outdir="\$OUTDIR",vcpus=$VCPUS,limit=$LIMIT,trigger=$TRIGGER,capture_pa=on,values=on \\
    "\${LOADVM[@]}" \\
    #
    # ─── YOUR BOOT FLAGS GO HERE (replace this comment block) ────────
    # Add your usual -cpu, -drive, pflash firmware, -nic, cloud-init
    # seed, etc. — everything you normally boot this guest with, minus
    # any -accel/-machine/-smp/-m flags (all four are already set above —
    # -smp/-m via the SMP=/MEM= variables near the top of this script,
    # -accel/-machine inline; -cpu note: TCG cannot use 'host'; use a
    # named model, e.g. -cpu cortex-a76).
    # ─────────────────────────────────────────────────────────────────
RUNEOF
chmod +x "$RUN"

echo "OK: wrote $RUN"
echo "OK: wrote $META"
echo "Next: edit the boot-flags block in run_trace.sh, then see README.md"
